import Age from "./Age";
import ForgetPassword from "./forgetPassword";
import Gender from "./Gender";
import GetStarted from "./GetStarted";
import Goals from "./Goals";
import LogIn from "./LogIn";
import NewPassword from "./NewPassword";
import OnBoarding1 from "./OnBoarding1";
import OnBoarding2 from "./OnBoarding2";
import OnBoarding3 from "./OnBoarding3";
import OnBoarding4 from "./OnBoarding4";
import Otp from "./Otp";
import Prefer1 from "./Prefer1";
import Prefer2 from "./Prefer2";
import SignUp from "./SignUp";
import SplashScreen from "./splash";
import ForYou from "./ForYou";
import Create from "./Create";
import Explore from "./Explore";
import Library from "./Library";
import Profile from "./Profile";

export { Library }
export { Explore }
export { Create }
export { ForYou }
export { Profile }
export { ForgetPassword }
export { Gender }
export { Goals }
export { LogIn }
export { NewPassword }
export { Otp }
export { Prefer1 }
export { Prefer2 }
export { SignUp }
export { GetStarted }
export { SplashScreen }
export { Age }
export { OnBoarding4 }
export { OnBoarding3 }
export { OnBoarding2 }
export { OnBoarding1 }
