export const NavigationRoute = {
  SplashScreen: 'SplashScreen',
  OnBoarding1: 'OnBoarding1',
  OnBoarding2: 'OnBoarding2',
  OnBoarding3: 'OnBoarding3',
  OnBoarding4: 'OnBoarding4',
  GetStarted: 'GetStarted',
  LogIn: 'LogIn',
  SignUp: 'SignUp',
  ForgetPassword: 'Forget Password',
  Otp: 'Otp',
  NewPassword: 'NewPassword',
  Gender: 'Gender',
  Age: 'Age',
  Goals: 'Goals',
  Prefer1: 'Prefer1',
  Prefer2: 'Prefer2',
  ForYou: 'ForYou',
  Library: 'Library',
  Create: 'Create',
  Profile: 'Profile',
  Explore: 'Explore',
  bottomNavigation: 'bottomNavigation',
  Subscription: 'Subscription',
  DarkMode: 'DarkMode',
  SubscriptionForm: 'SubscriptionForm',
  ChatScreen: 'ChatScreen',
  UserList: 'UserList',
};
