import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  SafeAreaView: {flex: 1, backgroundColor: 'white'},
  ScrollView: {marginVertical: 20},
  Logo_View: {marginHorizontal: 20, flexDirection: 'row'},
  Logo_Style: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  Logo_Text: {
    fontSize: 24,
    fontWeight: '800',
    color: '#000000',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  line_view: {
    borderWidth: 1,
    borderColor: '#EFEFEF',
    marginVertical: 5,
  },
  Steaks_View: {
    marginVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderColor: '#EFEFEF',
  },
  Steaks_Img: {width: 22, height: 25, resizeMode: 'contain'},
  Steaks_Text_View: {
    alignSelf: 'center',
    alignItems: 'flex-start',
    marginRight: 20,
  },
  Steaks_Text: {fontSize: 16, color: '#191C20'},
  container: {
    marginTop: 50,
    paddingHorizontal: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  imageContainer: {
    marginRight: 10,
  },
  image: {
    width: 71,
    height: 83,
    resizeMode: 'contain',
  },
  flatListContent: {
    paddingHorizontal: 25,
  },
  itemContainer: {
    marginRight: 10,
  },
  Flat_image: {
    width: 161,
    height: 215,
    resizeMode: 'contain',
  },
  titleText: {
    fontSize: 14,
    color: '#191C20',
    fontWeight: '500',
    marginHorizontal: 5,
    marginTop: 5,
  },
  listContainer: {
    flexDirection: 'row',
    marginVertical: 5,
    marginHorizontal: 25,
  },
  productContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    padding: 5,
    borderRadius: 5,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    marginRight: 10,
  },
  productImage: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  productText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#191C20',
    marginHorizontal: 5,
    alignSelf: 'center',
  },
  Daily_view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#0166FF',
    marginHorizontal: 20,
    borderRadius: 10,
  },
  Daily_Text: {fontSize: 24, color: '#FFFFFF', fontWeight: '700'},
  Get_it_Touch: {flexDirection: 'row', marginVertical: 15},
  Get_it_Text: {alignSelf: 'center', color: '#ffffff'},
  RightArrow_style: {
    width: 12,
    height: 14,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginHorizontal: 6,
  },
  Img_Summary_Style: {width: 90, height: 120},
  Categories_View: {marginHorizontal: 25, marginVertical: 10},
  Categories_Text: {fontSize: 16, fontWeight: '700', color: '#191C20'},
  Heading_View: {marginHorizontal: 25, marginVertical: 20},
  Heading_Title: {fontSize: 18, fontWeight: '700', color: '#191C20'},
  Heading_Text: {fontSize: 13, fontWeight: '400', color: '#8C8C8C'},
  Rateing_Style: {width: 70, height: 70, resizeMode: 'contain'},
  Challenges_View: {
    flexDirection: 'row',
    marginHorizontal: 25,
    backgroundColor: '#FFEBCE',
    justifyContent: 'space-between',
    padding: 20,
    borderRadius: 10,
  },
  Challenges_Text: {color: '#191C20', fontSize: 20, fontWeight: '700'},
  Challenges_5_day: {color: '#FF9900', marginTop: 15},
  Manage_View: {
    marginHorizontal: 25,
    marginVertical: 15,
    padding: 20,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: '#EBEBEB',
  },
  Manage_Img: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginHorizontal: 5,
  },
  Manage_Text: {fontSize: 12, color: '#191C20'},
  Manage_Img_View_Time: {flexDirection: 'row', marginVertical: 10},
  Manage_Img_View_Dollar: {flexDirection: 'row', marginHorizontal: 10},
  Manage_Img_View_Trophie: {flexDirection: 'row'},
  Button_View: {flex: 1, justifyContent: 'flex-end'},
  button: {
    backgroundColor: '#F6F6F6',
    marginVertical: 5,
    padding: 15,
    borderRadius: 8,
  },
  buttonText: {color: '#191C20', alignSelf: 'center'},
  Flatlist_Container: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginVertical: 10,
  },
  summaryContainer: {
    borderWidth: 1,
    padding: 10,
    borderColor: '#EFEFEF',
    borderRadius: 12,
    marginRight: 10,
  },
  summaryImage: {
    width: 148,
    height: 103,
    resizeMode: 'contain',
  },
  summaryTitle: {
    color: '#303030',
  },
  ideaContainer: {
    flexDirection: 'row',
  },
  ideaIcon: {
    width: 10,
    height: 14,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginRight: 10,
  },
  ideaText: {
    color: '#191C20',
  },
});
export default styles;
